spring.application.name=aninode-backend
# Puerto
server.port=8080

# Conexión a la base de datos de Clever Cloud
spring.datasource.url=${DB_URL:jdbc:mysql://b38g4itxebgbhic7yn5t-mysql.services.clever-cloud.com:3306/b38g4itxebgbhic7yn5t?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:ufptzozwyecmfqmu}
spring.datasource.password=${DB_PASSWORD:oInqnrcxyR19VyCYzWk0}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect